name: vortex_market
description: "A new Flutter project for VORTEX MARKET."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 
  cupertino_icons: ^1.0.8

  # --- إدارة الحالة (State Management) ---
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1

  # --- التصميم والاستجابة (UI & Responsiveness) ---
  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cached_network_image: ^3.4.1

  # --- الربط والبيانات (Data & Networking) ---
  dio: ^5.9.2
  shared_preferences: ^2.5.5
  connectivity_plus: ^6.1.4
  web_socket_channel: ^3.0.0

  # --- الدفع (Payment) ---
  flutter_stripe: ^11.0.0

  # --- الصور والوسائط (Images & Media) ---
  image_picker: ^1.2.1
  image_cropper: ^8.0.0

  # --- الإشعارات (Notifications) ---
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.0

  # --- إضافات أخرى ---
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  password_strength_checker: ^1.2.4
  url_launcher: ^6.3.2
  flutter_staggered_animations: ^1.1.1
  flutter_rating_bar: ^4.0.1
       
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- إضافة الصور هنا (Assets) ---
  assets:
    - lib/assets/images/         # هذا سيشمل صورة الخلفية وأي صور أخرى تضعها في هذا المجلد
    # - assets/icons/          # (اختياري) إذا كان لديك أيقونات خاصة